#!/bin/bash

while getopts ":hH:u:p:d:t:" option; do
    case "${option}" in
        h)
            echo "Usage : installdb -H <host> [-u <user>] [-p <password>] -d <database> -f <filename>"
            exit;
            ;;
        H)
            readonly host=${OPTARG}
            ;;
        u)
            readonly user=${OPTARG}
            ;;
        p)
            readonly pwd=${OPTARG}
            ;;
        d)
            readonly db=${OPTARG}
            ;;
        f)
            readonly file=${OPTARG}
            ;;
        \?)
            echo "Invalid option !"
            exit;
            ;;
    esac
done

if [ -z "${host}" ]; then
    echo "Required -H option was not set !";
    exit 2
fi;

if [ -z "${db}" ]; then
    echo "Required -d option was not set !";
    exit 2 
fi;

if [ -z "${file}" ]; then
    echo "Required -f option was not set !";
    exit 2 
fi;

mysqlcommand= "mysql";

if [ -n "${user}" ]; then
    mysqlcommand= "${mysqlcommand} -u${user}"
fi

if [ -n "${pwd}" ]; then
    mysqlcommand="${mysqlcommand} -p${pwd}"
fi

checkdb = $(${mysqlcommand} --batch --skip-column-names -e "SHOW DATABASES LIKE '"${db}"';" | grep "${db}" > /dev/null; echo "$?")

if [ ! ${checkdb} -eq 0 ]; then
    eval "${mysqlcommand} -e \"source ${file}\"
fi;

exit;

