#!/bin/bash

if [ -z "$ENV_TIMEZONE" ]; then
    export ENV_TIMEZONE="France/Paris"
fi

if [ -z "$ENV_DBHOST" ]; then
    export ENV_DBHOST="db"
fi

if [ -z "$ENV_DBUSER" ]; then
    export ENV_DBUSER="root"
fi

if [ -z "$ENV_DBPWD" ]; then
    export ENV_DBPWD="root"
fi

if [ -z "$ENV_DBNAME" ]; then
    export ENV_DBNAME="discord-assistantbot"
fi

if [ -z "$ENV_BRANCH" ]; then
    export ENV_BRANCH="master"
fi

ln -snf /usr/share/zoneinfo/${ENV_TIMEZONE} /etc/localtime && echo ${ENV_TIMEZONE} > /etc/timezone

cd /var/lib/discord-assistantbot

if [ ! -d ".git" ]; then
    git clone https://github.com/BakaKiller/discord-assistantbot.git --single-branch --branch ${ENV_BRANCH}
fi

echo "Updating..."
git pull
echo "Updated !"

echo "NPM Installing..."
npm install
echo "Installed !"

echo "Done ! Now, let's start the bot !"
exec "$@"